backend:
  name: github
  repo: agursoyy/vuepress-documentor
  branch: master

publish_mode: editorial_workflow

media_folder: "docs/.vuepress/public/images"
public_folder: "/upload"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
