backend:
  name: github
  repo: agursoyy/vuepress-documentor
  branch: master

publish_mode: editorial_workflow

media_folder: "docs/.vuepress/public/images"
public_folder: "/upload"

collections:
  - name: "getting-started"
    label: "Getting Started"
    folder: "docs/getting-started"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "getting-started-notifications"
    label: "Getting Started-Notifications"
    folder: "docs/getting-started/notifications"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "getting-started-cargo"
    label: "Getting Started-Cargo"
    folder: "docs/getting-started/cargo"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "public-api-method-details"
    label: "Public API Method Details"
    folder: "docs/public api method details"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
