backend:
  name: github
  repo: agursoyy/vuepress-documentor
  branch: master

publish_mode: editorial_workflow

media_folder: "docs/.vuepress/public/images"
public_folder: "/upload"

collections:
  - name: "getting-started"
    label: "Getting Started"
    folder: "docs/getting-started"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "building-a-request"
    label: "Building a Request"
    folder: "docs/building-a-request"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Code", name: "code", widget: "code" }
